version: "3.8"

services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: covertype_db
      MYSQL_ROOT_PASSWORD: covertype_db
    ports:
      - "3306:3306"
    networks:
      - common_network
    volumes:
      - db:/var/lib/minesql
    
  load-database:
    build:
      context: ./database
    image: yemoncad/mlops_covertype-database:dbt2
    depends_on:
      - db
    environment:
      - USER_DB=root
      - PASS_DB=covertype_db
      - IP_SERVER=db
      - NAME_DB=covertype_db_X
    ports:
      - '8502:8502'
    networks:
      - common_network
    volumes:
      - train_data:/database/data

  train-model:
    build:
      context: ./train
    image: yemoncad/mlops_covertype-train_model:traint2
    depends_on:
      - db
      - load-database
    environment:
      - USER_DB=root
      - PASS_DB=covertype_db
      - IP_SERVER=db
      - NAME_DB=covertype_db_X
    ports:
      - '8503:8503'
    networks:
      - common_network
    volumes:
      - model:/train/models

  inference:
    build:
      context: ./inference
    image: yemoncad/mlops_covertype-inference:inferencet2
    depends_on:
      - db
      - load-database
      - train-model
    environment:
      - USER_DB=root
      - PASS_DB=covertype_db
      - IP_SERVER=db
      - NAME_DB=covertype_db_z
    ports:
      - '8504:8504'
    networks:
      - common_network
    volumes:
      - model:/train/models

  logging:
    build:
      context: ./logging
    image: yemoncad/mlops_covertype-logging:loggingt2
    depends_on:
      - db
      - load-database
      - train-model
      - inference
    environment:
      - USER_DB=root
      - PASS_DB=covertype_db
      - IP_SERVER=db
      - NAME_DB=covertype_db_z
    ports:
      - '8505:8505'
    networks:
      - common_network
    volumes:
      - train_data:/database/data

  app:
    build:
      context: ./app
    image: yemoncad/mlops_covertype-app:appt3
    depends_on:
      - db
      - load-database
      - train-model
      - inference
      - logging
    environment:
      - USER_DB=root
      - PASS_DB=db_train
      - IP_SERVER=db
      - NAME_DB=db_z
    ports:
      - '8506:8506'
    networks:
      - common_network
    volumes:
      - train_data:/database/data
      - model:/train/models

volumes:
  db:
    driver: local
  train_data:
    driver: local
  model:
    driver: local

networks:
  common_network:
    driver: bridge